version: '2.1'
orbs:
  slack: circleci/slack@4.1
  maven: circleci/maven@1.3.0
jobs:
  start-cicd:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - run: echo "Start compile my app!"
      - slack/notify:
          event: fail
          mentions: '@everyone'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
  compile:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - slack/notify:
          event: fail
          mentions: '@everyone'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  test-and-deploy:
    jobs:
      - start-cicd:
          context: slack
      - maven/test:
          context: slack
          requires:
            - start-cicd
          pre-steps:
            - run: mvn clean install -X
          post-steps:
            - slack/notify:
                event: fail
                mentions: '@everyone'
                template: basic_fail_1
            - slack/notify:
                event: pass
                template: success_tagged_deploy_1
