version: '2.1'
orbs:
  slack: circleci/slack@4.1
  maven: circleci/maven@1.3.0
  android: circleci/android@2.0.3
jobs:
  android-build:
    executor:
      name: android/android-machine
      resource-class: large
      tag: 2021.10.1
    steps:
      - checkout
      - android/restore-gradle-cache
      - android/restore-build-cache
      - slack/notify:
          event: fail
          mentions: '@everyone'
          template: basic_fail_1
      - slack/notify:
          event: pass
          template: success_tagged_deploy_1
workflows:
  test-and-deploy:
    jobs:
      - android-build:
          context: slack
